accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'account'
urlpatterns = [

    path('login/', views.MyLoginView.as_view(), name="login"),

    path('loginjudge/', views.loginjudgeview, name="loginjudge"),
    path('agreement/', views.AgreementView.as_view(), name="agreement"),

    path('user_data_input/', views.UserDataInput.as_view(), name='user_data_input'),
    path('user_data_confirm/', views.UserDataConfirm.as_view(), name='user_data_confirm'),
    path('user_data_create/', views.UserDataCreate.as_view(), name='user_data_create'),

    path('cansel/', views.UserDeleteConfirmView.as_view(), name='cansel'),
    path('canselconp/', views.UserDeleteView.as_view(), name='canselconp'),
    ]

barter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings
# 設定の settings ではない！by 竹前


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('barter_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from barter_app.common import NgWord# NGワード
from django.core.validators import MinLengthValidator

class Prefectures2(models.Model):
    """都道府県モデル"""
    
    code = models.IntegerField(verbose_name='都道府県コード', primary_key=True)
    name = models.CharField(verbose_name='都道府県名', max_length=30,null=True,blank=True)

    class Meta:
        verbose_name_plural = 'Prefectures2'
    
    def __str__(self):
        return self.name

class CustomUser(AbstractUser):

    class Meta:
        verbose_name_plural = 'CustomUser'
    
    # ユーザーアイコン
    usericon = models.ImageField(verbose_name='ユーザーアイコン', blank=True, null=True)
    # ユーザー名
    username = models.CharField(verbose_name='ユーザー名', validators=[NgWord], max_length=15, blank=True, null=True)
    # 生年月日
    birthday_regex = RegexValidator(regex=r'[12]\d{3}-[01][0123456789]-\d{2}', message = ("※入力内容をご確認ください。"))
    birthday = models.CharField(verbose_name='生年月日', validators=[birthday_regex], max_length=10, blank=True, null=True)
    # メールアドレス
    email = models.EmailField(verbose_name='メールアドレス', max_length=30, blank=True, null=True)
    # 電話番号
    tel_number_regex = RegexValidator(regex=r'^[0-9]+$', message = ("※入力内容をご確認ください。"))
    telephone = models.CharField(verbose_name='電話番号', validators=[tel_number_regex, MinLengthValidator(10)], max_length=11, default="")
    # 都道府県
    prefecture = models.ForeignKey(Prefectures2, verbose_name='都道府県',max_length=5, on_delete=models.PROTECT, blank=True, null=True)
    # 住所
    address = models.CharField(verbose_name='住所(市区町村・番地)', validators=[NgWord], max_length=40, blank=True, null=True)
    # 住所2
    address2 = models.CharField(verbose_name='住所2(建物名)', validators=[NgWord], max_length=40, blank=True, null=True)
    # 郵便番号
    postalcode_regex = RegexValidator(regex=r'^[0-9]+$', message = ("※入力内容をご確認ください。"))
    zip_code = models.CharField(verbose_name='郵便番号', validators=[postalcode_regex, MinLengthValidator(7)], max_length=7, blank=True, null=True)
    # 希望商品
    comment = models.TextField(verbose_name='希望商品：あなたが欲しい商品を記入して下さい。', validators=[NgWord], max_length=100, blank=True, null=True)

    # チケット
    ticket = models.IntegerField(verbose_name='チケット枚数', default=0, null=True)

    #ログイン判定
    login_flg = models.BooleanField(verbose_name='初回ログインはTrue', default='True', null=True)
    #良い評価
    good_evaluation = models.IntegerField(verbose_name='良かった評価', default=0, null=True)
    #悪い評価
    bad_evaluation = models.IntegerField(verbose_name='悪かった評価', default=0, null=True)

    
    def __str__(self):
        return self.username

accounts/forms.py
from django.contrib.auth import forms as auth_forms
from django import forms

class LoginForm(auth_forms.AuthenticationForm):
    username = forms.EmailField(label='メールアドレス', max_length=254, required=True)
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control col-9'
        self.fields['username'].widget.attrs['placeholder'] = 'メールアドレスを入力してください。'

        self.fields['password'].widget.attrs['class'] = 'form-control col-9'
        self.fields['password'].widget.attrs['placeholder'] = 'パスワードを入力してください。'


#新規会員登録
from allauth.account.forms import SignupForm

class CustomSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'



#ユーザー情報登録
from accounts.models import CustomUser, Prefectures2

class UserCreateForm(forms.ModelForm):
    last_name = forms.CharField(label='姓', max_length=254)
    first_name = forms.CharField(label='名', max_length=254)
    birthday = forms.CharField(label='生年月日', max_length=10)
    telephone = forms.CharField(label='電話番号', max_length=11)
    zip_code = forms.CharField(label='郵便番号', max_length=254)
    prefecture = forms.ModelChoiceField(queryset=Prefectures2.objects.all())
    address = forms.CharField(label='住所(市区町村・番地)', max_length=254)
    address2 = forms.CharField(label='住所2(建物名)', max_length=254, required=False)


    class Meta:
        model = CustomUser
        fields = ('last_name', 'first_name', 'birthday', 'telephone', 'zip_code', 'prefecture', 'address', 'address2') 

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control col-10'
        self.fields['last_name'].widget.attrs['placeholder'] = '例：山田'

        self.fields['first_name'].widget.attrs['class'] = 'form-control col-10'
        self.fields['first_name'].widget.attrs['placeholder'] = '例：太郎'

        self.fields['birthday'].widget.attrs['class'] = 'form-control col-10'
        self.fields['birthday'].widget.attrs['placeholder'] = '例：2001-02-03'

        self.fields['telephone'].widget.attrs['class'] = 'form-control col-10'
        self.fields['telephone'].widget.attrs['placeholder'] = '例：09012345678'


        self.fields['zip_code'].widget.attrs['class'] = 'form-control col-10 p-postal-code'
        self.fields['zip_code'].widget.attrs['placeholder'] = '例：0101234'

        self.fields['prefecture'].widget.attrs['class'] = 'form-control col-10 p-region-id'
        self.fields['prefecture'].widget.attrs['placeholder'] = '例：都道府県'

        self.fields['address'].widget.attrs['class'] = 'form-control col-10 p-locality p-street-address'
        self.fields['address'].widget.attrs['placeholder'] = '例：見本市見本町1-23-4'

        self.fields['address2'].widget.attrs['class'] = 'form-control col-10 p-extended-address'
        self.fields['address2'].widget.attrs['placeholder'] = '例：〇〇ビル301'

accounts/views.py
from django.shortcuts import redirect, render

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from . import forms
from django.urls import reverse_lazy

from django.views import generic

from django.views.decorators.http import require_POST
from .forms import UserCreateForm
from django.contrib.auth import get_user_model
from accounts.models import CustomUser

from django.http import HttpResponseRedirect
from django.urls import reverse
from barter_app.models import Goods,ChatRoom,Offer
from django.db.models import Q 


User = get_user_model()


#初回ログイン判定
def loginjudgeview(request):
    user = request.user
    log_f = user.login_flg
    if log_f == True:
        return redirect('account:user_data_input')
    else:
        return HttpResponseRedirect(reverse('barter_app:home', args=request))


#ログイン
class MyLoginView(LoginView):
    form_class = forms.LoginForm
    template_name = "account/login.html"


# 規約ページ
class AgreementView(generic.TemplateView):
    template_name = 'agreement.html'



#ユーザー情報入力
class UserDataInput(generic.FormView):
    model = CustomUser
    template_name = 'user_data_input.html'
    form_class = UserCreateForm


    def form_valid(self, form):
        return render(self.request, 'user_data_input.html', {'form': form})
    
    


#ユーザ情報の確認
class UserDataConfirm(generic.FormView):
    form_class = UserCreateForm

    def form_valid(self, form):
        return render(self.request, 'user_data_confirm.html', {'form': form})

    def form_invalid(self, form):
        return render(self.request, 'user_data_input.html', {'form': form})

#ユーザデータ登録
class UserDataCreate(generic.UpdateView):
    model = CustomUser
    form_class = UserCreateForm
    success_url = reverse_lazy('barter_app:home')

    def post(self, request):
        user = request.user
        form = UserCreateForm(request.POST or None, instance=request.user)
        form.save()
        log_f = user.login_flg
        if log_f == True:
            user.login_flg = False
            user.save()
        return redirect("barter_app:home")
        #return render(self.request, 'home.html')
    
    def form_invalid(self, form):
        return render(self.request, 'user_data_input.html', {'form': form})


#退会ページ
class UserDeleteConfirmView(generic.TemplateView):
    template_name = 'cansel.html'


#退会処理
class UserDeleteView(LoginRequiredMixin, generic.View):
    def get(self, *args, **kwargs):
        user = User.objects.get(email=self.request.user.email)
        user.is_active = False
        user.save()
        goods_list = Goods.objects.filter(user=user)
        offer_list = Offer.objects.filter(user=user)
        for goods in goods_list:
            goods.trade = 3
            goods.save()
        for offer in offer_list:
            offer.trade = 5
            offer.save()
        room_list = ChatRoom.objects.filter(Q(user1=user.pk) | Q(user2=user.pk))
        for room in room_list:
            room.is_active = False
            room.save()
        #auth_logout(self.request)
        return render(self.request,'cansel_after.html')

accounts/templates/agreement.html
{% extends 'base.html' %}
{% load static %}

{% block title %}利用規約{% endblock %}


{% block contents %}

<div class="container">
    <section class="main_cont effect d_02">
        <div class="my-div-style">
            <h2 class="midasi" style="text-align: center;">利用規約</h2>       
            <div class="agreement effect">

                <h2>この利用規約（以下、「本規約」といいます。）は、BARTOWN（以下、「当社」といいます。）が、このウェブサイト上で提供するサービス（以下、「本サービス」といいます。）の利用条件を定めるものです。
                    <br>登録ユーザーの皆さま（以下、「ユーザー」といいます。）には、本規約に従って、本サービスをご利用いただきます。</h2>
                <table>
                    <tr>
                        <th>第1条（適用）</th>
                    </tr>
                    <tr>
                        <td>本規約は、ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。当社は本サービスに関し、本規約のほか、ご利用にあたってのルール等、各種の定め（以下、「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず、本規約の一部を構成するものとします。本規約の規定が前条の個別規定の規定と矛盾する場合には、個別規定において特段の定めなき限り、個別規定の規定が優先されるものとします。</td>
                    </tr>
                    <tr>
                        <th>第2条（利用登録）</th>
                    </tr>
                    <tr>
                        <td>本サービスにおいては、登録希望者が本規約に同意の上、当社の定める方法によって利用登録を申請し、当社がこれを承認することによって、利用登録が完了するものとします。当社は、利用登録の申請者に以下の事由があると判断した場合、利用登録の申請を承認しないことがあり、その理由については一切の開示義務を負わないものとします。
                            <li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
                            <li>本規約に違反したことがある者からの申請である場合</li>
                            <li>その他、当社が利用登録を相当でないと判断した場合</li>
                        </td>
                    </tr>
                    <tr>
                        <th>第3条（ユーザーIDおよびパスワードの管理）</th>
                    </tr>
                    <tr>
                        <td>ユーザーは、自己の責任において、本サービスのユーザーIDおよびパスワードを適切に管理するものとします。ユーザーは、いかなる場合にも、ユーザーIDおよびパスワードを第三者に譲渡または貸与し、もしくは第三者と共用することはできません。当社は、ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には、そのユーザーIDを登録しているユーザー自身による利用とみなします。ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は、当社に故意又は重大な過失がある場合を除き、当社は一切の責任を負わないものとします。</td>
                    </tr>
                    <tr>
                        <th>第4条（利用料金および支払方法）</th>
                    </tr>
                    <tr>
                        <td>
                            ユーザーは、本サービスの有料部分の対価として、当社が別途定め、本ウェブサイトに表示する利用料金を、当社が指定する方法により支払うものとします。
                            ユーザーが利用料金の支払を遅滞した場合には、ユーザーは年14．6％の割合による遅延損害金を支払うものとします。
                        </td>
                    </tr>
                    <tr>
                        <th>第5条（禁止事項）</th>
                    </tr>
                    <tr>
                        <td>
                            ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。
                            
                            <li>法令または公序良俗に違反する行為</li>
                            <li>犯罪行為に関連する行為</li>
                            <li>本サービスの内容等、本サービスに含まれる著作権、商標権ほか知的財産権を侵害する行為</li>
                            <li>当社、ほかのユーザー、またはその他第三者のサーバーまたはネットワークの機能を破壊したり、妨害したりする行為</li>
                            <li>本サービスによって得られた情報を商業的に利用する行為</li>
                            <li>当社のサービスの運営を妨害するおそれのある行為</li>
                            <li>不正アクセスをし、またはこれを試みる行為</li>
                            <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
                            <li>不正な目的を持って本サービスを利用する行為</li>
                            <li>本サービスの他のユーザーまたはその他の第三者に不利益、損害、不快感を与える行為</li>
                            <li>他のユーザーに成りすます行為</li>
                            <li>当社が許諾しない本サービス上での宣伝、広告、勧誘、または営業行為</li>
                            <li>面識のない異性との出会いを目的とした行為</li>
                            <li>当社のサービスに関連して、反社会的勢力に対して直接または間接に利益を供与する行為</li>
                            <li>その他、当社が不適切と判断する行為</li>
                            
                        </td>
                    </tr>
                    <tr>
                        <th>第6条（本サービスの提供の停止等）</th>
                    </tr>
                    <tr>
                        <td>
                            当社は、以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
                            <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
                            <li>地震、落雷、火災、停電または天災などの不可抗力により、本サービスの提供が困難となった場合</li>
                            <li>コンピュータまたは通信回線等が事故により停止した場合</li>
                            <li>その他、当社が本サービスの提供が困難と判断した場合</li>
                            <li>当社は、本サービスの提供の停止または中断により、ユーザーまたは第三者が被ったいかなる不利益または損害についても、一切の責任を負わないものとします。</li>
                        </td>
                    </tr>
                    <tr>
                        <th>第7条（利用制限および登録抹消）</th>
                    </tr>
                    <tr>
                        <td>
                            当社は、ユーザーが以下のいずれかに該当する場合には、事前の通知なく、ユーザーに対して、本サービスの全部もしくは一部の利用を制限し、またはユーザーとしての登録を抹消することができるものとします。
                            <li>本規約のいずれかの条項に違反した場合</li>
                            <li>登録事項に虚偽の事実があることが判明した場合</li>
                            <li>料金等の支払債務の不履行があった場合</li>
                            <li>当社からの連絡に対し、一定期間返答がない場合</li>
                            <li>本サービスについて、最終の利用から一定期間利用がない場合</li>
                            <li>その他、当社が本サービスの利用を適当でないと判断した場合</li>
                            <li>当社は、本条に基づき当社が行った行為によりユーザーに生じた損害について、一切の責任を負いません。</li>
                        </td>
                    </tr>
                    <tr>
                        <th>第8条（退会）</th>
                    </tr>
                    <tr>
                        <td>ユーザーは、当社の定める退会手続により、本サービスから退会できるものとします。</td>
                    </tr>
                    <tr>
                        <th>第9条（保証の否認および免責事項）</th>
                    </tr>
                    <tr>
                        <td>
                            当社は、本サービスに事実上または法律上の瑕疵（安全性、信頼性、正確性、完全性、有効性、特定の目的への適合性、セキュリティなどに関する欠陥、エラーやバグ、権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。
                            <br>当社は、本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし、本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合、この免責規定は適用されません。
                            <br>前項ただし書に定める場合であっても、当社は、当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し、または予見し得た場合を含みます。）について一切の責任を負いません。また、当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は、ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。
                            <br>当社は、本サービスに関して、ユーザーと他のユーザーまたは第三者との間において生じた取引、連絡または紛争等について一切責任を負いません。
                        </td>
                    </tr>
                    <tr>
                        <th>第10条（サービス内容の変更等）</th>
                    </tr>
                    <tr>
                        <td>当社は、ユーザーに通知することなく、本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし、これによってユーザーに生じた損害について一切の責任を負いません。</td>
                    </tr>
                    <tr>
                        <th>第11条（利用規約の変更）</th>
                    </tr>
                    <tr>
                        <td>当社は、必要と判断した場合には、ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお、本規約の変更後、本サービスの利用を開始した場合には、当該ユーザーは変更後の規約に同意したものとみなします。</td>
                    </tr>
                    <tr>
                        <th>第12条（個人情報の取扱い）</th>
                    </tr>
                    <tr>
                        <td>当社は、本サービスの利用によって取得する個人情報については、当社「プライバシーポリシー」に従い適切に取り扱うものとします。</td>
                    </tr>
                    <tr>
                        <th>第13条（通知または連絡）</th>
                    </tr>
                    <tr>
                        <td>ユーザーと当社との間の通知または連絡は、当社の定める方法によって行うものとします。当社は,ユーザーから,当社が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。</td>
                    </tr>
                    <tr>
                        <th>第14条（権利義務の譲渡の禁止）</th>
                    </tr>
                    <tr>
                        <td>ユーザーは、当社の書面による事前の承諾なく、利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し、または担保に供することはできません。</td>
                    </tr>
                    <tr>
                        <th>第15条（準拠法・裁判管轄）</th>
                    </tr>
                    <tr>
                        <td>
                            本規約の解釈にあたっては、日本法を準拠法とします。
                            本サービスに関して紛争が生じた場合には、当社の本店所在地を管轄する裁判所を専属的合意管轄とします。
                        </td>
                    </tr>
                </table>
                <br>
                <div class="d-flex justify-content-center">
                    <a class="btn btn-info" href="javascript:history.back()" style="background-color: #0066FF; text-align: center;">戻る</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

accounts/templates/cansel.html
{% extends 'base.html' %}

{% block title %}退会{% endblock %}

{% block active_signup %}active{% endblock %}

{% block contents %}
<div class="container">
    <section class="main_cont effect d_02">        
        <h2 class="midasi" style="text-align: center;">退会</h2>
        <form method="" action="{% url 'account:canselconp' %}">
            {% csrf_token %}
            <h4 style="margin: 80px auto 80px 10px; text-align: center;">本当に退会してもよろしいですか？</h4>

            <div class="d-flex justify-content-center">
                <a href="javascript:void(0);" onclick="window.history.back();" class="btn btn-danger" style="margin-right: 5px;">キャンセル</a>
                <button class="btn btn-primary" name="next" value="confirm" type="submit" style="margin-left: 5px;">退会</button>
            </div>
        </form>
    </section>

</div>
{% endblock %}

accounts/templates/cansel_after.html
{% extends 'signup_base.html' %}

{% block title %}退会完了{% endblock %}

{% block active_signup %}active{% endblock %}

{% block contents %}
<div class="container">
    <section class="main_cont effect d_02">        
        <h2 class="midasi" style="text-align: center;">退会完了</h2>
        <br>
        <br>
        <br>
        <h2 style="margin: auto auto 300px 10px;">ご利用ありがとうございました。</h2>
    </section>
</div>
{% endblock %}

accounts/templates/user_data_confirm.html
{% extends "signup_base.html" %}
{% load field_extras %}

{% block title %}会員情報確認{% endblock %}

{% block active_signup %}active{% endblock %}

{% block contents %}
<style>
    .sign_main {
        margin: 0px 250px 0px 250px;
    }
    @media screen and (max-width:1000px) {
        .sign_main {
            margin: 0px;
        }
    }
</style>
<div class="container">
    <section class="main_cont effect d_02">
        <h2 class="midasi" style="text-align: center;">会員情報確認</h2>        
        {% csrf_token %} 
        <table class="table">    
            <tr>
                <div class="form-group row">
                    <td><label class="col col-form-label"><strong>姓：</strong></label></td>
                    <td><div class="col">{{ form.last_name.value }}</div></td>
                </div>
            </tr>
            <tr>
                <div class="form-group row">
                    <td><label class="col col-form-label"><strong>名：</strong></td>
                    <td><div class="col">{{ form.first_name.value }}</div></td>
                </div>
            </tr>
            <tr>
                <div class="form-group row">
                    <td><label class="col col-form-label"><strong>生年月日：</strong></label></td>
                    <td><div class="col">{{ form.birthday.value }}</div></td>
                </div>
            </tr>
            <tr>
                <div class="form-group row">
                    <td><label class="col col-form-label"><strong>電話番号：</strong></label></td>
                    <td><div class="col">{{ form.telephone.value }}</div></td>
                </div>
            </tr>
            <tr>
                <div class="form-group row">
                    <td><label class="col col-form-label"><strong>郵便番号：</strong></label></td>
                    <td><div class="col">{{ form.zip_code.value }}</div></td>
                </div>
            </tr>
            <tr>
                <div class="form-group row">
                    <td><label class="col col-form-label"><strong>都道府県：</strong></label></td>
                    <td><div class="col">{% data_verbose form.prefecture.value %}</div></td>
                </div>
            </tr>
            <tr>
                <div class="form-group row">
                    <td><label class="col col-form-label"><strong>住所(市区町村・番地)：</strong></label></td>
                    <td><div class="col">{{ form.address.value }}</div></td>
                </div>
            </tr>
            <tr>
                <div class="form-group row">
                    <td><label class="col col-form-label"><strong>住所2(建物名等)：</strong></label></td>
                    <td><div class="col">{{ form.address2.value }}</div></td>
                </div>
            </tr>
        </table>

        <div class="d-flex justify-content-center">
            <table>
                <tr>
                    <form action="{% url 'account:user_data_input' %}" method="POST">
                        <td><button type="submit" class="btn btn-danger" style="margin: 10px 5px auto auto;">修正</button></td>
                        {% for field in form %}{{ field.as_hidden }}{% endfor %}
                        {% csrf_token %}
                    </form>
                    <hr>
                    <form action="{% url 'account:user_data_create' %}" method="POST">
                        <td><button type="submit" class="btn btn-primary" style="margin: 10px auto auto 5px;">確定</button></td>
                        {% for field in form %}{{ field.as_hidden }}{% endfor %}
                        {% csrf_token %}
                    </form>
                </tr>
            </table>
        </div>
        <br>
        <br>
    </section>
</div>
{% endblock %}

accounts/templates/user_data_input.html
{% extends "signup_base.html" %}

{% block title %}会員情報登録{% endblock %}

{% block active_signup %}active{% endblock %}

{% block contents %}
    <style>
        .sign_main {
            margin: auto 250px auto 250px;
        }
        @media screen and (max-width:1000px) {
            .sign_main {
                margin: auto 5px auto 5px;
            }
        }
    </style>
    <div class="container">
        <section class="main_cont effect d_02">
            <h2 class="midasi" style="text-align: center;">会員情報登録</h2>
            <p>※初回ログイン時のみ入力</p>
            <form action="{% url 'account:user_data_confirm' %}" method="POST" class="h-adr">
                {% csrf_token %}
                <span class="p-country-name" style="display:none;">Japan</span>

                {{ form.non_field_errors }}
                    <div class="form-group">
                        <table class="table">    
                            <tr>
                                <div class="form-group row">
                                    <td class="col-4"><label><strong>姓： <span class="required">必須</span></strong></label></td>
                                    <td class="col-8"><a style="color: red;">{{ form.last_name.errors }}</a>{{ form.last_name }}</td>
                                </div>
                            </tr>
                            <tr>
                                <div class="form-group row">
                                    <td class="col-4"><label><strong>名： <span class="required">必須</span></strong></td>
                                    <td class="col-8"><a style="color: red;">{{ form.first_name.errors }}</a>{{ form.first_name }}</td>
                                </div>
                            </tr>
                            <tr>
                                <div class="form-group row">
                                    <td class="col-4"><label><strong>生年月日： <span class="required">必須</span></strong></label></td>
                                    <td class="col-8">
                                    <a style="color: red;">{{ form.birthday.errors }}</a>
                                    <input type="date" name="birthday" value="{{form.birthday.value}}" class="form-control col-10" id="id_birthday">
                                    <p>右側のカレンダーアイコンクリックで楽々登録。</p>    
                                </div>
                            </tr>
                            <tr>
                                <div class="form-group row">
                                    <td class="col-4"><label><strong>電話番号： <span class="required">必須</span></strong></label></td>
                                    <td class="col-8"><a style="color: red;">{{ form.telephone.errors }}</a>{{ form.telephone }}</td>
                                </div>
                            </tr>
                            <tr>
                                <div class="form-group row">
                                    <td class="col-4"><label><strong>郵便番号： <span class="required">必須</span></strong></label></td>
                                    <td class="col-8"><a style="color: red;">{{ form.zip_code.errors }}</a>{{ form.zip_code }}</td>
                                </div>
                            </tr>
                            <tr>
                                <div class="form-group row">
                                    <td class="col-4"><label><strong>都道府県： <span class="required">必須</span></strong></label></td>
                                    <td class="col-8"><a style="color: red;">{{ form.prefecture.errors }}</a>{{ form.prefecture }}</td>
                                </div>
                            </tr>
                            <tr>
                                <div class="form-group row">
                                    <td class="col-4"><label><strong>住所(市区町村・番地)： <span class="required">必須</span></strong></label></td>
                                    <td class="col-8"><a style="color: red;">{{ form.address.errors }}</a>{{ form.address }}</td>
                                </div>
                            </tr>
                            <tr>
                                <div class="form-group row">
                                    <td class="col-4"><label><strong>住所2(建物名等)：</strong></label></td>
                                    <td class="col-8"><a style="color: red;">{{ form.address2.errors }}</a>{{ form.address2 }}</td>
                                </div>
                            </tr>
                        </table>
                    </div>
                    
                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary" style="margin-top: 10px;">確認</button>
                </div>
                <br>
                <br>
            </form>
        </section>
    </div>
{% endblock %}