barter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings
# 設定の settings ではない！by 竹前


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('barter_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

barter_app/urls.py
from django.urls import path
from . import views
from . import tests

app_name = 'barter_app'


urlpatterns = [

    path('',views.IndexView.as_view(), name="index"),
    
    path('goods-list/', views.GoodsListView.as_view(), name="goods_list"),
    path('goods-create/', views.GoodsCreateView.as_view(), name="goods_create"),

    path('',views.IndexView.as_view(), name="index"),
    path('q_a/', views.Q_aView.as_view(), name="q_a"),

    path('inquiry/',views.InquiryForm.as_view(), name="inquiry"),

    path('home/', views.HomeView.as_view(), name="home"),

    path('mypage/', views.MypageView.as_view(), name="mypage"),
    path('settings_change_account/', views.SettingsChangeAccount, name="settings_change_account"),

    path('inquiry/',views.InquiryForm.as_view(), name="inquiry"),

    path('settings_change_account_icon_only/', views.SettingsChangeAccountIcon, name="settings_change_account_icon_only"),
    path('change_password/', views.change_password, name="change_password"),
    path('change_success/', views.change_successView.as_view(), name="change_success"),

    path('goods_list/', views.GoodsListView.as_view(), name="goods_list"),
    path('goods_create/', views.GoodsCreateView.as_view(), name="goods_create"),
    path('goods_detail/<int:pk>/', views.goods_detail, name="goods_detail"),
    path('goods_delete/', views.goods_delete,name="goods_delete"),
    path('offer_create/', views.GoodsOffer, name="offer_create"),
    path('offer_select/', views.OfferSelect, name="offer_select"),
    path('my_offer/', views.my_offer, name="my_offer"),
    path('offer_detail/', views.offer_detail, name="offer_detail"),
    path('trading_history/', views.trading_history,name="trading_history"),
    path('trading_history_end/', views.trading_history_end,name="trading_history_end"),
    path('trading_detail/', views.trading_detail,name="trading_detail"),
    path('trading_contact/', views.trading_contact,name="trading_contact"),
    path('chat_message/', views.chat_message,name="chat_message"),
    path('chat_room_list/', views.chat_room_list,name="chat_room_list"),
    path('user_notice/', views.user_notice,name="user_notice"),
    path('user_list/', views.user_list,name="user_list"),
    path('transaction_example/', views.transaction_example,name="transaction_example"),
    path('transaction_detail/<int:pk>/', views.transaction_detail, name="transaction_detail"),

    path('make-data/', tests.makeData,name="make_data"), # 都道府県、カテゴリデータ読み込み
    path('goods_copy/', tests.goods_copy,name="goods_copy"), # 商品データ保存
    path('goods_read/', tests.goods_read,name="goods_read"), # 商品データ読み込み

    path('goods-search/', views.goods_search,name="goods_search"),
    path('trade-search/', views.trade_search,name="trade_search"),

    path('prefecture_list/', views.prefectures_select,name="prefecture_list"),
    path('prefecture/<int:code>/', views.prefecture,name="prefecture"),

    path('ticket/', views.TicketView.as_view(), name="ticket"),
    path('pay-comp/', views.PayCompView.as_view(), name="pay_comp"),

    path('seller_information/', views.seller_info, name="seller_information"),
    path('like/', views.like, name="like"),
    path('like_list/', views.likelist, name="likelist"),
    path('user_evaluation/', views.user_evaluation, name="user_evaluation"),
    path('user_evaluation_list/<int:pk>/', views.user_evaluation_list, name="user_evaluation_list"),

    path('my-display', views.MydisplayView.as_view(), name="my_display"),
    path('todos/', views.TodosView, name="todos"),
    path('tododel/<int:pk>/', views.tododelview, name="todo_del"),
    path('address_print/', views.address_print, name="address_print"),
    path('seller_goods_detail/<int:pk>/', views.seller_goods_detail, name="seller_goods_detail"),

]

barter_app/models.py
from django.db import models
from accounts.models import CustomUser
from barter_app.common import NgWord# NGワード
from django.contrib.auth import get_user_model

# 商品の状態の選択肢
status_choice = (('新品未使用品','新品未使用品'), ('美品','美品'), ('普通','普通'), ('悪い','悪い'), ('非常に悪い','非常に悪い'),)


class Prefectures(models.Model):
    """都道府県モデル"""
    
    code = models.IntegerField(verbose_name='都道府県コード', primary_key=True)
    name = models.CharField(verbose_name='都道府県名', max_length=30)

    class Meta:
        verbose_name_plural = 'Prefectures'
    
    def __str__(self):
        return self.name

class Category1(models.Model):
    """大分類カテゴリーモデル"""

    cate1 = models.CharField(verbose_name='カテゴリー1', max_length=30)

    class Meta:
        verbose_name_plural = 'Category1'
    
    def __str__(self):
        return self.cate1

class Category2(models.Model):
    """詳細カテゴリーモデル"""
    
    cate1 = models.ForeignKey(Category1, verbose_name='カテゴリー1', on_delete=models.PROTECT, blank=True, null=True)
    cate2 = models.CharField(verbose_name='カテゴリー2', max_length=30)

    class Meta:
        verbose_name_plural = 'Category2'
    
    def __str__(self):
        return str(self.cate1) + ' - ' + str(self.cate2)

class Goods(models.Model):
    """出品商品モデル"""

    name = models.CharField(verbose_name='商品名', validators=[NgWord], max_length=30)
    status = models.CharField(verbose_name='商品状態', default='', max_length=10, blank=True, null=True, choices=status_choice)
    category = models.ForeignKey(Category2, verbose_name='カテゴリー', on_delete=models.PROTECT, blank=True, null=True)
    user = models.ForeignKey(CustomUser, verbose_name='出品者', on_delete=models.PROTECT)
    prefecture = models.ForeignKey(Prefectures, verbose_name='都道府県', on_delete=models.PROTECT, blank=True, null=True)
    content = models.TextField(verbose_name='商品説明', validators=[NgWord], max_length=200, default='', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    photo2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    photo3 = models.ImageField(verbose_name='写真3', blank=True, null=True)
    photo4 = models.ImageField(verbose_name='写真4', blank=True, null=True)
    photo5 = models.ImageField(verbose_name='写真5', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='出品日時', auto_now_add=True)
    confirm = models.BooleanField(verbose_name='登録完了済み', default=True)
    trade = models.IntegerField(verbose_name='1:出品中2:取引成立3:出品取下げ', default=1)

    class Meta:
        verbose_name_plural = 'Goods'
    
    def __str__(self):
        return self.name


class Offer(models.Model):
    """交換申し込みモデル"""

    user = models.ForeignKey(CustomUser, verbose_name='交換申し込み者', on_delete=models.PROTECT)
    goods = models.ForeignKey(Goods, verbose_name='相手の商品', on_delete=models.PROTECT, blank=True, null=True)
    name = models.CharField(verbose_name='自分の商品名', validators=[NgWord], max_length=30)
    category = models.ForeignKey(Category2, verbose_name='カテゴリー', on_delete=models.PROTECT, blank=True, null=True)
    status = models.CharField(verbose_name='商品状態', default='', max_length=10, blank=True, null=True, choices=status_choice)
    prefecture = models.ForeignKey(Prefectures, verbose_name='都道府県', on_delete=models.PROTECT, blank=True, null=True)
    content = models.TextField(verbose_name='商品説明', validators=[NgWord], max_length=200, default='', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    photo2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    photo3 = models.ImageField(verbose_name='写真3', blank=True, null=True)
    photo4 = models.ImageField(verbose_name='写真4', blank=True, null=True)
    photo5 = models.ImageField(verbose_name='写真5', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='申し込み日時', auto_now_add=True)
    confirm = models.BooleanField(verbose_name='登録完了済み', default=True)
    trade = models.IntegerField(verbose_name='1:申請中2:取引成立3:拒否4:出品終了5:申請取下げ', default=1)
    goods_registed_id = models.IntegerField(verbose_name='登録済み商品の場合ID,新規申し込みの場合:-1', blank=True, null=True, default=-1)

    class Meta:
        verbose_name_plural = 'Offer'
    
    def __str__(self):
        return self.name

class TradingHistory(models.Model):
    """取引履歴モデル"""

    goods = models.ForeignKey(Goods, verbose_name='出品者の商品', on_delete=models.PROTECT, blank=True, null=True)
    offer = models.ForeignKey(Offer, verbose_name='申込者の商品', on_delete=models.PROTECT, blank=True, null=True)
    completion_at = models.DateTimeField(verbose_name='取引成立日時', auto_now_add=True)
    sending1 = models.IntegerField(verbose_name='出品商品 1:未発送2:発送済み3:受け取り完了4:評価済み', default=1)
    sending2 = models.IntegerField(verbose_name='申込商品 1:未発送2:発送済み3:受け取り完了4:評価済み', default=1)
    status = models.IntegerField(verbose_name='1:取引中2:取引完了', default=1)
    g_eva = models.BooleanField(verbose_name='出品者評価済み', default=False)
    o_eva = models.BooleanField(verbose_name='申込者評価済み', default=False)
    
    class Meta:
        verbose_name_plural = 'TradingHistory'
    
    def __str__(self):
        return str(self.goods) + ' と ' + str(self.offer) + ' の交換'

class TradingMessage(models.Model):
    """取引メッセージ"""

    trading = models.ForeignKey(TradingHistory, verbose_name='取引履歴', on_delete=models.PROTECT, blank=True, null=True)
    sender = models.IntegerField(verbose_name='送信者ID', blank=True, null=True)
    receiver = models.IntegerField(verbose_name='受信者ID', blank=True, null=True)
    subject = models.CharField(verbose_name='件名', default='', max_length=30, blank=True, null=True)
    message = models.TextField(verbose_name='メッセージ', validators=[NgWord], default='', max_length=200, blank=True, null=True)
    completion_at = models.DateTimeField(verbose_name='送信日時', auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'TradingMessage'
    
    def __str__(self):
        return str(self.sender) + 'と' + str(self.receiver) + 'のメッセージ'
        
evaluation_choice = (('good', '良かった'), ('bad', '悪かった'),)
class Evaluation(models.Model):
    """受取評価画面"""

    user = models.ForeignKey(CustomUser, verbose_name='評価される側', on_delete=models.PROTECT)
    trading = models.ForeignKey(TradingHistory, verbose_name='取引履歴', on_delete=models.PROTECT, blank=True, null=True)
    eva_user = models.IntegerField(verbose_name='評価者ID', blank=True, null=True)
    eva_username = models.CharField(verbose_name='評価者名',default='', max_length=15, blank=True, null=True)
    eva_radio = models.CharField(verbose_name="受取評価",default='good', max_length=10)
    review = models.TextField(verbose_name='評価のコメント', validators=[NgWord], default='', max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='評価日時', auto_now_add=True, blank=True, null=True)
    confirm = models.BooleanField(verbose_name='評価確定済み',default=False)
    class Meta:
        verbose_name_plural = 'Evaluation'

    def __str__(self):
        return str(self.user) + ' ' + str(self.eva_radio)

class FavUser(models.Model):
    """お気に入り"""

    user = models.ForeignKey(CustomUser, verbose_name='お気に入り(人)', on_delete=models.CASCADE, related_name='send_user')
    item = models.ForeignKey(Goods, verbose_name='お気に入り(もの)', on_delete=models.CASCADE, related_name='receive_item')

    class Meta:
        verbose_name_plural = 'Favorites'

    def __str__(self):
        return str(self.user)


class ChatRoom(models.Model):
    """チャットルーム"""

    user1 = models.IntegerField(verbose_name='ユーザ1', blank=True, null=True)
    user2 = models.IntegerField(verbose_name='ユーザ2', blank=True, null=True)
    last_at = models.DateTimeField(verbose_name='最終メッセージ日時', auto_now_add=True)
    is_active = models.BooleanField(verbose_name='アクティブか（退会したらFalse）',default=True)
    
    class Meta:
        verbose_name_plural = 'ChatRoom'
    
    def __str__(self):
        return str(self.user1) + ' ' + str(self.user2) + str(self.last_at)

class ChatMessage(models.Model):
    """チャットメッセージ"""

    room = models.ForeignKey(ChatRoom, verbose_name='チャットルーム', on_delete=models.PROTECT, blank=True, null=True)
    sender = models.IntegerField(verbose_name='送信者ID', blank=True, null=True)
    message = models.TextField(verbose_name='メッセージ', default='', max_length=200,validators=[NgWord])
    created_at = models.DateTimeField(verbose_name='送信日時', auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'ChatMessage'
    
    def __str__(self):
        return self.message + str(self.created_at)

class GoodsComment(models.Model):
    """商品コメント欄"""

    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.PROTECT, blank=True, null=True)
    user = models.ForeignKey(CustomUser, verbose_name='コメント者', on_delete=models.PROTECT)
    comment = models.TextField(verbose_name='コメント', default='', max_length=100,validators=[NgWord])
    created_at = models.DateTimeField(verbose_name='送信日時', auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'GoodsComment'
    
    def __str__(self):
        return self.comment + str(self.created_at)

class TodosList(models.Model):
    """ Todoリスト """

    goods = models.ForeignKey(Goods, verbose_name='Goodsのid', on_delete=models.PROTECT, null=True, blank=True)
    offer = models.ForeignKey(Offer, verbose_name='OfferModelのid',on_delete=models.PROTECT, null=True, blank=True)
    trade = models.ForeignKey(TradingHistory, verbose_name='TradingHistoryのid',on_delete=models.PROTECT, null=True, blank=True)
    user = models.ForeignKey(CustomUser, verbose_name='出品者,(チャットだと受信者)', on_delete=models.PROTECT)
    photo1 = models.ImageField(verbose_name='出品者の写真1', blank=True, null=True)
    todo_flg = models.IntegerField(verbose_name='出品者 1:拒否2:未発送3:発送済4:受取完了5:取引終了6:削除', null=True, blank=True)
    offer_flg = models.IntegerField(verbose_name='申請者 0:申請中1:申請取下げ2:未発送3:発送済4:受取完了5:取引終了6:削除', default=0, null=True, blank=True)
    created_at = models.DateTimeField(verbose_name='日時(やることリスト登録日時)', auto_now=True)

barter_app/templates/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}マイページ{% endblock %}

{% block contents %}
<link  rel="stylesheet" href="{% static 'mypage.css' %}">

<script>
    function goClick() {location.href = "{% url 'barter_app:settings_change_account_icon_only' %}";}
</script>

<section class="main_cont effect d_02">
    <div class="container">    
            <h2 class="midasi" style="text-align:center">マイページ</h2>

            <div style="display: flex;">
                <div class="button_solid008">
                    <h4 style="margin-top: 20px;"><strong>商品の管理</strong></h4>
                    <a style="margin-top: 0;" href="{% url 'barter_app:my_display' %}">出品済一覧</a>
                    <a href="{% url 'barter_app:my_offer' %}">交換申請一覧</a>
                    <a href="{% url 'barter_app:trading_history' %}">取引中一覧</a>
                    <a href="{% url 'barter_app:trading_history_end' %}">取引完了一覧</a>
    
                    <h4 style="margin-top: 20px;"><strong>その他設定</strong></h4>
                    <a style="margin-top: 0;" href="{% url 'barter_app:settings_change_account' %}">ユーザー情報変更</a>
                    <a href="{% url 'barter_app:change_password' %}">パスワード変更</a>
                    <a style="color: #961f1f;" href="{% url 'account_logout' %}">ログアウト</a>
                </div>

            <div class="icon_name_eva">
                {% if user.usericon %}
                    <img src="{{ user.usericon.url }}" class="mypage_icon button" onclick="goClick()">
                    <div class="my_name">{{ user.username }}</div>
                {% else %}
                    <img src="{% static 'img/user-icon.png' %}" class="mypage_icon button" style="background-color: white;" onclick="goClick()">
                    <div class="my_name">{{ user.username }}</div>
                {% endif %}

                <div class="my_eva">良い評価：{{ user.good_evaluation }}<br>悪い評価：{{ user.bad_evaluation }}</div>


                <div class="button_solid009" style="width: 50px;">
                    <form method="post" name="seller" action="{% url 'barter_app:user_evaluation_list' user.pk %}">
                        {% csrf_token %}
                        <input type="hidden" name="page" value="mypage">
                        <a style="color: #284d70;" href="javascript:seller.submit()">評価詳細</a>
                    </form>
                    <form method="post" name="tick2" action="{% url 'barter_app:ticket' %}">
                        {% csrf_token %}
                        <input type="hidden" name="page" value="mypage">
                        <a style="color: #157a2b;" href="javascript:tick2.submit()">チケット枚数 {{ user.ticket }}枚</a>
                    </form>
                    <a style="color: #d19b05;" href="{% url 'barter_app:likelist' %}">お気に入り一覧</a>
                </div>
            </div>
            
        </div>
    </div>
</section>
{% endblock %}

barter_app/templates/seller_goods_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}商品詳細{% endblock %}

{% block head %}
<style>
    .photo4 {
        margin-left: 290px;
    }
    @media (max-width: 1200px) { /*1200px以下の時*/
        .photo4{
            margin-left: 240px;
        }
    }
</style>
<script>
    var img_src = new Array({% if object.photo1 %}"{{ object.photo1.url }}"{%endif%}{% if object.photo2 %},"{{ object.photo2.url }}"{%endif%}{% if object.photo3 %},"{{ object.photo3.url }}"{%endif%}{% if object.photo4 %},"{{ object.photo4.url }}"{%endif%}{% if object.photo5 %},"{{ object.photo5.url }}"{%endif%});
    var i = 0;

    function henkou() {

      if (i == img_src.length-1) {
        i = 0;
      } else {
        i ++;
      }
      document.getElementById("photo_img").src = img_src[i];
    }
    function img_change(num){
        i = num
        document.getElementById("photo_img").src = img_src[i];
    }
  </script>
{% endblock %}

{% block contents %}
<link  rel="stylesheet" href="{% static 'seller_style.css' %}">
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2 class="midasi" style="text-align:center">商品詳細</h2>
        </div>
        
    </div>
    <div class="row">
        <div class="col-sm-12">
            {% if user == object.user %}
                <p style="text-align: center;">あなたが出品した商品です</p>
            {% endif %}
            {%if object.trade == 2%}<h3 class="" style="text-align:center">この商品は取引成立済みです</h3>{%endif%}
            {%if object.trade == 3%}<h3 class="" style="text-align:center">この商品は出品取り消しされました</h3>{%endif%}
            {%if user.pk%}
                {%if object.trade == 1%} 
                    {% if user == object.user %}
                    <form method="POST" action="{% url 'barter_app:goods_delete' %}" enctype='multipart/form-data'>
                        {% csrf_token %}
                        <button class="btn btn-danger" name="goods_id" value="{{object.pk}}" style="float: right;" type="submit">商品を削除する</button>
                    </form>
                    {% else %}
                    <form method="POST" action="{% url 'barter_app:offer_select' %}" enctype='multipart/form-data'>
                        {% csrf_token %}
                        <input type="hidden" name="back1" value="s_info">
                        <button class="btn btn-primary" name="goods_id" value="{{object.pk}}" style="float: right;" type="submit">交換を申し込む</button>
                    </form>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
    </div>

    <div class="row" style="background: #dddddd;padding-top: 10px">
        <div class="col-sm-  mx-auto">
            <strong>商品名</strong>
            <div><h3>{{ object.name }}</h3></div>
        </div>
    </div>      
    <div class="row" style="background: #dddddd;padding-bottom: 10px">
        <div class="col-12 mx-auto" style="text-align: center;">
            {% if object.photo1 %}
                <img id="photo_img" class="photo_size" src="{{ object.photo1.url }}" onClick="henkou()"/>
            {% else %}
                <img src="{% static 'img/noimage2.png' %}" alt="noimage" style="width: 300px; height: 300px;"/>        
            {% endif %}
        </div>
    </div>
    {% if object.photo2 %}
        <div class="row" style="background: #dddddd;">
            <div class="col-sm- mx-auto">
                {% if object.photo1 %}
                    <img src="{{ object.photo1.url }}" onClick="img_change(0)" style="width: 100px; height: 100px;"/>
                {% endif %}
                {% if object.photo2 %}
                    <img src="{{ object.photo2.url }}" onClick="img_change(1)" style="width: 100px; height: 100px;"/>
                {% endif %}
                {% if object.photo3 %}
                    <img src="{{ object.photo3.url }}" onClick="img_change(2)" style="width: 100px; height: 100px;"/>
                {% endif %}
                {% if object.photo4 %}
                    <img src="{{ object.photo4.url }}" onClick="img_change(3)" style="width: 100px; height: 100px;"/>
                {% endif %}
                {% if object.photo5 %}
                    <img src="{{ object.photo5.url }}" onClick="img_change(4)" style="width: 100px; height: 100px;"/>
                {% endif %}
            </div>
        </div>
    {% endif %}
    <br>
    <div class="row">
        <div class="col-3">
            <strong>商品説明</strong>
        </div>
        <div class="col-9">
            {{ object.content|linebreaksbr }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-3">
            <strong>カテゴリー</strong>
        </div>
        <div class="col-9">
            {{ object.category|linebreaksbr }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-3">
            <strong>出品地域</strong>
        </div>
        <div class="col-9">
            {{ object.user.prefecture|linebreaksbr }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-3">
            <strong>商品状態</strong>
        </div>
        <div class="col-9">
            {{ object.status|linebreaksbr }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-3">
            <strong>希望商品</strong>
        </div>
        <div class="col-9">
            {{ object.user.comment|linebreaksbr }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-3">
            <strong>作成日時</strong>
        </div>
        <div class="col-9">
            {{ object.created_at }}
        </div>
    </div>
    <br>
    {%if user.pk%}
        {% if user != object.user %}
            <div class="row">
                <div class="col-3">
                    <strong>出品者</strong>
                </div>
                <br>
                <br>
                <div class="col-9">
                    <form method="POST" action="{% url 'barter_app:seller_information' %}">
                        {% csrf_token %}
                        <input type=hidden name="g_user" value="{{object.user.pk}}">
                        <input type="hidden" name="goods_pk" value="{{object.pk}}">
                        <input type="hidden" name="back1" value="s_info">
                        <button class="btn-sticky" type="submit">
                            {% if object.user.usericon %}
                                <img src="{{ object.user.usericon.url }}" class="user-icon-MY">    {{ object.user.username }}
                            {% else %}
                                <img src="{% static 'img/user-icon.png' %}" class="user-icon-MY">    {{ object.user.username }}
                            {% endif %}
                        </button>
                    </form>
                    <br>

                    <form method="POST" action="{% url 'barter_app:chat_message' %}#message_form" enctype='multipart/form-data'>
                        {% csrf_token %}
                        <input type=hidden name="g_user" value="{{object.user.pk}}">
                        <input type="hidden" name="back1" value="s_info">
                        <input type="hidden" name="sgd" value="sgd">
                        <input type="hidden" name="goods_pk" value="{{object.pk}}">
                        <button class="btn btn-primary" name="" value="" type="submit">出品者にメッセージを送る</button>
                    </form>
                    <br>
                    {% include 'like.html' %}
                    <script type="text/javascript">
                        $(document).ready(function(event){
                            $(document).on('click', '#like', function(event){
                                event.preventDefault();
                                $.ajax({
                                    type: 'POST',
                                    url: "{% url 'barter_app:like' %}",
                                    data: {
                                        'article_id': '{{ object.pk }}',
                                        'csrfmiddlewaretoken': '{{ csrf_token }}'},
                                    dataType: 'json',
                                    success: function(response){
                                        selector = document.getElementsByName('article_id');
                                        if(response.liked){
                                            $(selector).html('<i class="fas fa-star unlike-btn"> お気に入り解除</i>');
                                        }
                                        else {
                                            $(selector).html('<i class="far fa-star like-btn"> お気に入り追加</i>');
                                        }
                                    }
                                });
                            });
                        });
                    </script>
                </div>
            </div>    
        {% endif %}

        {% if form.errors %}
            <ul>
                {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="row">
            <div class="col-sm-10 mx-auto">
                {%for come in comments%}
                <hr style="border: 0.5px dashed gainsboro;">
                <div class="row">
                    <table>
                        <tr>
                            <th style="font-weight: 400; font-size: 14px;">{{come.user}} | {{come.created_at}}</th>
                        </tr>
                        <tr>
                            <td style="font-weight: 900;">　{{come.comment}}</td>
                        </tr>
                    </table>
                </div>
                {%endfor%}
        
                <form method="POST" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <table class="table">
                        {{ form.as_table }}
                    </table>
                    <input type="hidden" name="goods_id" value="{{object.id}}">
                    <div style="text-align: center;">
                        <a>※上部のコメントは誰でも閲覧可能です。内容に注意してください。</a>
                    </div>
                    <br>
                    <div style="text-align: center;">
                        <form method="POST" enctype='multipart/form-data'>
                            {% csrf_token %}
                            <i class="fa fa-send"><button class="btn btn-primary" name="next" value="confirm" type="submit" style="background-color: #0066FF; padding: 10px 20px;">&#xf1d8; 送信</button></i>
                        </form>
                    </div>
                </form>
            </div>
        </div>
    {%else%}
    <br><hr>
    <h3>交換申請するには<a href="{% url 'account_login' %}">ログイン</a>、または<a href="{% url 'account_signup' %}">会員登録</a>してください</h3>
    {% endif %}
</div>
{% endblock %}

barter_app/templates/trading_contact_completion.html
{% extends 'base.html' %}
{% load static %}

{% block title %}メッセージ送信{% endblock %}

{% block contents %}
<link rel="stylesheet" href="{% static 'All_style.css' %}" />
<section class="main_cont effect d_02">
<div class="content">

    <h2 class="my-div-style" style="text-align:center">送信完了しました</h2>
    
    <h3 style="text-align:center">メッセージを送信しました</h3>
    <form method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
        
        <input type="hidden" name="trade_pk" value="{{trade.id}}" id="id_name">
        
        <button class="btn btn-primary" name="next" value="" type="submit">取引連絡に戻る</button>
    </form>

</div>
</section>
<br>
<br>
{% endblock %}